const productSpecs = {
  1: { colour: 'Yellow, orange and green', dimensions: '36L x 24W x 4H cm', weight: '650 g', brand: 'Craftigen' },
  2: { colour: 'Multicolour patchwork', dimensions: '21L x 14W x 2H cm', weight: '320 g', brand: 'Craftigen' },
  3: { colour: 'Blue, orange and tan', dimensions: '40L x 30W x 8H cm', weight: '720 g', brand: 'Craftigen' },
  4: { colour: 'Rose gold and white', dimensions: '30L x 30W x 4H cm', weight: '850 g', brand: 'Craftigen' },
  5: { colour: 'Antique gold', dimensions: '18L x 18W x 24H cm', weight: '900 g', brand: 'Craftigen' },
  6: { colour: 'Silver', dimensions: '45L x 30W x 3H cm', weight: '780 g', brand: 'Craftigen' },
  7: { colour: 'Gold and multicolour', dimensions: '20L x 12W x 28H cm', weight: '1.1 kg', brand: 'Craftigen' },
  8: { colour: 'Polished gold', dimensions: '8L x 8W x 15H cm', weight: '280 g', brand: 'Craftigen' },
  9: { colour: 'Red, white and multicolour', dimensions: '12L x 9W x 10H cm', weight: '340 g', brand: 'Craftigen' },
  10: { colour: 'Antique black and gold', dimensions: '12L x 12W x 18H cm', weight: '420 g', brand: 'Craftigen' },
  11: { colour: 'Antique brass', dimensions: '22L x 16W x 10H cm', weight: '1.2 kg', brand: 'Craftigen' },
  12: { colour: 'Orange, blue, green, red and yellow', dimensions: '28L x 18W x 10H cm', weight: '950 g', brand: 'Craftigen' },
  13: { colour: 'Deep red', dimensions: '24L x 6W x 16H cm', weight: '300 g', brand: 'Craftigen' },
  14: { colour: 'Antique bronze', dimensions: '18L x 18W x 8H cm', weight: '620 g', brand: 'Craftigen' },
  15: { colour: 'Multicolour', dimensions: '26L x 10W x 18H cm', weight: '700 g', brand: 'Craftigen' },
  16: { colour: 'Cream, red and gold', dimensions: '15L x 15W x 14H cm', weight: '520 g', brand: 'Craftigen' },
  17: { colour: 'Red and blue', dimensions: '12L x 12W x 10H cm each', weight: '600 g', brand: 'Craftigen' },
  18: { colour: 'Antique brass', dimensions: '9L x 9W x 4H cm each', weight: '420 g', brand: 'Craftigen' },
  19: { colour: 'Off-white with floral print', dimensions: '36L x 12W x 34H cm', weight: '480 g', brand: 'Craftigen' },
  20: { colour: 'Yellow and black', dimensions: '18L x 8W x 14H cm each', weight: '560 g', brand: 'Craftigen' },
  21: { colour: 'Clear glass', dimensions: '10L x 10W x 16H cm each', weight: '850 g', brand: 'Craftigen' },
  22: { colour: 'Antique gold', dimensions: '35L x 25W x 3H cm', weight: '740 g', brand: 'Craftigen' },
  23: { colour: 'Blue and white', dimensions: '30L x 22W x 10H cm', weight: '1 kg', brand: 'Craftigen' },
  24: { colour: 'Gold and blue', dimensions: '22L x 8W x 30H cm', weight: '460 g', brand: 'Craftigen' },
  25: { colour: 'Copper brown and clear', dimensions: '8L x 8W x 12H cm each', weight: '900 g', brand: 'Craftigen' },
  26: { colour: 'Blue, black and gold', dimensions: '32L x 24W x 8H cm', weight: '820 g', brand: 'Craftigen' },
  27: { colour: 'Pink, green and natural beige', dimensions: '30L x 30W x 24H cm', weight: '490 g', brand: 'Craftigen' },
  28: { colour: 'Natural beige', dimensions: '34L x 24W x 12H cm', weight: '1.3 kg', brand: 'Craftigen' },
  29: { colour: 'Natural bamboo', dimensions: '24L x 12W x 20H cm', weight: '380 g', brand: 'Craftigen' },
  30: { colour: 'Orange, yellow and brown', dimensions: '60L x 2W x 80H cm', weight: '350 g', brand: 'Craftigen' },
  31: { colour: 'Brown, orange and black', dimensions: '45L x 2W x 65H cm each', weight: '520 g', brand: 'Craftigen' },
  32: { colour: 'Red, blue and multicolour', dimensions: '20L x 12W x 18H cm', weight: '450 g', brand: 'Craftigen' },
};

const ItemsData = [
  {
    id: 1,
    title: 'King Procession Rectangle Tray',
    category: 'Serveware',
    price: 795,
    reviews: 270,
    rating: 4.1,
    material: 'Printed wooden tray',
    delivery: 'Free delivery by Wednesday',
    badge: 'Best Seller',
    description: 'A decorative rectangle tray with procession-inspired artwork for serving, styling, and festive gifting.',
    image: '/img/products/cards_tray.jpeg',
  },
  {
    id: 2,
    title: 'Handmade Diary Journal',
    category: 'Stationery',
    price: 595,
    reviews: 450,
    rating: 4.6,
    material: 'Paper with fabric cover',
    delivery: 'Free delivery by Tuesday',
    badge: 'Gift Pick',
    description: 'A handmade journal for notes, sketches, travel memories, and thoughtful everyday gifting.',
    image: '/img/products/Diary.jpeg',
  },
  {
    id: 3,
    title: 'King Procession Laptop Bag',
    category: 'Bags',
    price: 1299,
    reviews: 290,
    rating: 4.3,
    material: 'Printed canvas',
    delivery: 'Delivery in 3 days',
    badge: 'Popular',
    description: 'A craft-inspired laptop bag with practical storage and a distinct Indian motif.',
    image: '/img/products/LptopBag.jpeg',
  },
  {
    id: 4,
    title: 'Wall Clock Craft Edition',
    category: 'Wall Decor',
    price: 1350,
    reviews: 190,
    rating: 4.1,
    material: 'Metal and glass',
    delivery: 'Delivery in 5 days',
    badge: 'New Arrival',
    description: 'A craft-inspired wall clock that adds function and warmth to living rooms and work corners.',
    image: '/img/products/wall_clock.jpeg',
  },
  {
    id: 5,
    title: 'Brass Ganesh Aarti Accent',
    category: 'Pooja',
    price: 1100,
    reviews: 1230,
    rating: 4.3,
    material: 'Brass',
    delivery: 'Free delivery tomorrow',
    badge: 'Top Rated',
    description: 'A devotional brass Ganesh accent with a warm finish for pooja rooms, desks, and festive gifting.',
    image: '/img/products/Ganesha_arti.jpeg',
  },
  {
    id: 6,
    title: 'Elephant Wood Art Wall Frame',
    category: 'Wall Decor',
    price: 1250,
    reviews: 340,
    rating: 4.7,
    material: 'Metal decor',
    delivery: 'Free delivery by Thursday',
    badge: 'Highly Rated',
    description: 'An elephant-themed wall art piece crafted for living rooms, corridors, and gifting.',
    image: '/img/products/elephant_art.jpeg',
  },
  {
    id: 7,
    title: 'Radha Krishna Table Accent',
    category: 'Idols',
    price: 1890,
    reviews: 760,
    rating: 4.8,
    material: 'Hand-painted resin',
    delivery: 'Free delivery tomorrow',
    badge: 'Highly Rated',
    description: 'A devotional table accent with Radha Krishna detailing for decor, pooja corners, and gifting.',
    image: '/img/products/Radha_krishna.jpeg',
  },
  {
    id: 8,
    title: 'Brass Temple Bell',
    category: 'Pooja',
    price: 595,
    reviews: 63,
    rating: 4.5,
    material: 'Brass',
    delivery: 'Free delivery by Friday',
    badge: 'New',
    description: 'A polished brass temple bell with a clear tone and traditional silhouette.',
    image: '/img/products/krishna_bell.jpeg',
  },
  {
    id: 9,
    title: 'Designer Coffee Cup',
    category: 'Kitchen',
    price: 799,
    reviews: 870,
    rating: 4.4,
    material: 'Ceramic',
    delivery: 'Free delivery by Wednesday',
    badge: 'Deal',
    description: 'A designer ceramic coffee cup with a polished handmade look for daily use and gifting.',
    image: '/img/products/design_cofeecup.jpeg',
  },
  {
    id: 10,
    title: 'Decorative Candle Holder',
    category: 'Lighting',
    price: 650,
    reviews: 345,
    rating: 4.2,
    material: 'Metal',
    delivery: 'Free delivery by Thursday',
    badge: 'Cozy Decor',
    description: 'A decorative candle holder for ambient lighting, festive arrangements, and cozy corners.',
    image: '/img/products/candle.jpeg',
  },
  {
    id: 11,
    title: 'Brass Tortoise Aarti Deepak',
    category: 'Pooja',
    price: 2900,
    reviews: 460,
    rating: 4.5,
    material: 'Brass',
    delivery: 'Delivery in 3 days',
    badge: 'Premium',
    description: 'A statement tortoise-inspired brass deepak with a premium handmade finish.',
    image: '/img/products/tortoise_candle.jpeg',
  },
  {
    id: 12,
    title: 'Traditional Cup Set',
    category: 'Kitchen',
    price: 999,
    reviews: 568,
    rating: 4.5,
    material: 'Ceramic',
    delivery: 'Free delivery by Saturday',
    badge: 'Top Rated',
    description: 'A traditional cup set designed for tea, coffee, and elegant hosting.',
    image: '/img/products/cup_set.jpeg',
  },
  {
    id: 13,
    title: 'Red Velvet Sling Purse',
    category: 'Bags',
    price: 1250,
    reviews: 390,
    rating: 4.4,
    material: 'Velvet fabric',
    delivery: 'Delivery in 3 days',
    badge: 'Style Pick',
    description: 'A rich red sling purse for festive outfits, casual styling, and gifting.',
    image: '/img/products/redvelvet_purse.jpeg',
  },
  {
    id: 14,
    title: 'Copper Serving Bowl',
    category: 'Kitchen',
    price: 1499,
    reviews: 512,
    rating: 4.6,
    material: 'Copper alloy',
    delivery: 'Free delivery tomorrow',
    badge: 'Premium',
    description: 'A copper bowl for serving, festive dining, and traditional table settings.',
    image: '/img/products/copper_bowl.jpeg',
  },
  {
    id: 15,
    title: 'Royal Craft Figurine Set',
    category: 'Home Decor',
    price: 1640,
    reviews: 328,
    rating: 4.6,
    material: 'Painted terracotta',
    delivery: 'Free delivery by Thursday',
    badge: 'Fresh Arrival',
    description: 'A colorful royal figurine set that brings handcrafted character to shelves, consoles, and gifting corners.',
    image: '/img/products/Royal_free.jpg',
  },
  {
    id: 16,
    title: 'Hand Painted Flower Pot',
    category: 'Home Decor',
    price: 760,
    reviews: 214,
    rating: 4.3,
    material: 'Painted ceramic',
    delivery: 'Delivery in 3 days',
    badge: 'Artisan Pick',
    description: 'A bright hand painted flower pot for indoor plants, balconies, desks, and festive styling.',
    image: '/img/products/Flower_pot.jpg',
  },
  {
    id: 17,
    title: 'Small Terracotta Pot Set',
    category: 'Home Decor',
    price: 680,
    reviews: 301,
    rating: 4.2,
    material: 'Terracotta',
    delivery: 'Free delivery by Friday',
    badge: 'Value Pick',
    description: 'A compact terracotta pot set with handcrafted patterns for plants, corners, and table styling.',
    image: '/img/products/small_pot.jpg',
  },
  {
    id: 18,
    title: 'Decorative Diya Set',
    category: 'Pooja',
    price: 540,
    reviews: 642,
    rating: 4.5,
    material: 'Brass',
    delivery: 'Free delivery tomorrow',
    badge: 'Festive Pick',
    description: 'A colorful diya set for pooja, festive decor, rangoli corners, and gifting.',
    image: '/img/products/diya.jpg',
  },
  {
    id: 19,
    title: 'Handcrafted Jute Hand Bags',
    category: 'Bags',
    price: 1150,
    reviews: 286,
    rating: 4.4,
    material: 'Jute and cotton',
    delivery: 'Delivery in 4 days',
    badge: 'Eco Pick',
    description: 'A set of handcrafted jute bags for casual styling, shopping, and everyday utility.',
    image: '/img/products/hand_bags.jpg',
  },
  {
    id: 20,
    title: 'Wooden Elephant Decor Pair',
    category: 'Home Decor',
    price: 980,
    reviews: 227,
    rating: 4.4,
    material: 'Painted wood',
    delivery: 'Free delivery by Saturday',
    badge: 'Handmade',
    description: 'A wooden elephant decor pair with traditional detailing for shelves, entry consoles, and gifting.',
    image: '/img/products/elephants_wooden.jpg',
  },
  {
    id: 21,
    title: 'Painted Glass Jar Set',
    category: 'Kitchen',
    price: 890,
    reviews: 356,
    rating: 4.5,
    material: 'Clear glass',
    delivery: 'Free delivery by Wednesday',
    badge: 'Kitchen Pick',
    description: 'A painted glass jar set for dry storage, festive counters, and colorful kitchen styling.',
    image: '/img/products/glass_handcrafted.jpg',
  },
  {
    id: 22,
    title: 'Devotional God Art Frame',
    category: 'Wall Decor',
    price: 1380,
    reviews: 189,
    rating: 4.7,
    material: 'Brass-finish idol',
    delivery: 'Delivery in 4 days',
    badge: 'Gift Ready',
    description: 'A devotional art frame for pooja rooms, entry walls, and traditional home decor.',
    image: '/img/products/god_art.jpg',
  },
  {
    id: 23,
    title: 'Assorted Handicraft Gift Set',
    category: 'Gifting',
    price: 1790,
    reviews: 438,
    rating: 4.6,
    material: 'Blue pottery ceramic',
    delivery: 'Free delivery by Sunday',
    badge: 'Curated Set',
    description: 'A curated handicraft set with colorful handmade accents for festive hampers and special occasions.',
    image: '/img/products/items_set.jpg',
  },
  {
    id: 24,
    title: 'Traditional Decorative Mask',
    category: 'Wall Decor',
    price: 920,
    reviews: 176,
    rating: 4.4,
    material: 'Hand-painted mask',
    delivery: 'Delivery in 3 days',
    badge: 'Art Wall Pick',
    description: 'A traditional decorative mask for feature walls, entry spaces, studio corners, and cultural decor styling.',
    image: '/img/products/mask.jpg',
  },
  {
    id: 25,
    title: 'Handcrafted Glass Tumbler Set',
    category: 'Kitchen',
    price: 840,
    reviews: 264,
    rating: 4.5,
    material: 'Glass with painted tray',
    delivery: 'Free delivery by Friday',
    badge: 'Kitchen Pick',
    description: 'A handcrafted glass tumbler set for serving drinks, styling open shelves, and festive table settings.',
    image: '/img/products/glasses.jpg',
  },
  {
    id: 26,
    title: 'Artisan Serving Set',
    category: 'Serveware',
    price: 1490,
    reviews: 318,
    rating: 4.6,
    material: 'Painted ceramic serveware',
    delivery: 'Free delivery by Thursday',
    badge: 'Host Ready',
    description: 'A polished serving set designed for snacks, tea-time hosting, festive meals, and thoughtful gifting.',
    image: '/img/products/serving_set.jpg',
  },
  {
    id: 27,
    title: 'Handwoven Storage Basket',
    category: 'Home Decor',
    price: 790,
    reviews: 221,
    rating: 4.3,
    material: 'Handwoven cane',
    delivery: 'Delivery in 4 days',
    badge: 'Eco Pick',
    description: 'A handwoven storage basket for shelves, plants, towels, craft supplies, and everyday home organization.',
    image: '/img/products/handmade_basket.jpg',
  },
  {
    id: 28,
    title: 'Premium Handmade Decor Set',
    category: 'Gifting',
    price: 1990,
    reviews: 403,
    rating: 4.7,
    material: 'Bamboo and cane',
    delivery: 'Free delivery by Sunday',
    badge: 'Premium Set',
    description: 'A premium handmade decor set curated for festive gifting, housewarmings, and display-ready corners.',
    image: '/img/products/handmade_set.jpg',
  },
  {
    id: 29,
    title: 'Bamboo Craft Table Accent',
    category: 'Home Decor',
    price: 1180,
    reviews: 147,
    rating: 4.4,
    material: 'Bamboo',
    delivery: 'Delivery in 5 days',
    badge: 'Natural Craft',
    description: 'A bamboo craft accent that adds organic texture to consoles, side tables, shelves, and gifting displays.',
    image: '/img/products/bamboo_art.jpg',
  },
  {
    id: 30,
    title: 'Handcrafted Wall Hanging',
    category: 'Wall Decor',
    price: 1040,
    reviews: 235,
    rating: 4.5,
    material: 'Hand-painted wooden wall decor',
    delivery: 'Free delivery by Wednesday',
    badge: 'Wall Accent',
    description: 'A handcrafted wall hanging for adding color, craft detail, and warmth to living rooms or entry walls.',
    image: '/img/products/wall_hangings.jpg',
  },
  {
    id: 31,
    title: 'Decorative Wall Hanging Pair',
    category: 'Wall Decor',
    price: 1320,
    reviews: 198,
    rating: 4.6,
    material: 'Hand-painted wooden wall decor',
    delivery: 'Delivery in 3 days',
    badge: 'New Arrival',
    description: 'A decorative wall hanging pair made for gallery walls, festive styling, bedrooms, and gifting.',
    image: '/img/products/wall_hangings.2jpg.jpg',
  },
  {
    id: 32,
    title: 'Hand Painted Craft Accent',
    category: 'Home Decor',
    price: 980,
    reviews: 286,
    rating: 4.5,
    material: 'Hand-painted ceramic',
    delivery: 'Free delivery by Saturday',
    badge: 'Artisan New',
    description: 'A hand painted craft accent with colorful detailing for shelves, sideboards, and personal gifting.',
    image: '/img/products/hand_painted.jpg',
  },
].map((item) => ({
  ...item,
  ...(productSpecs[item.id] || {}),
}));

export default ItemsData;
